application: ca-gcp-developer
runtime: python27
api_version: 1
threadsafe: true
version: v1
module: tasks


handlers:
  - url: /.*
    script: tasks.app
    login: admin

basic_scaling:
  max_instances: 1
  idle_timeout: 10m
